# -*- coding: utf-8 -*-
"""PlanejadorDeViages.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m_Q8qZky3R62yaGrhWpCaA4aTLKM37wE
"""

# ==============================================
# Programa: Planejador de Viagens com Passeios e Remoção LIFO
# Autor: Fernando & Mateus
# Estrutura de Dados: PILHA (LIFO - Last In, First Out)
# ==============================================

pilha_viagem = []  # Lista que simula a pilha de destinos


# Função auxiliar para converter valores no formato brasileiro
def converter_valor(valor_str):
    """
    Converte valores no formato '1.200,50' ou '1200.50' para float (1200.50).
    Retorna None se o valor for inválido.
    """
    valor_str = valor_str.strip()
    valor_str = valor_str.replace(".", "").replace(",", ".")
    try:
        return float(valor_str)
    except ValueError:
        return None


while True:
    print("\n=======================================")
    print("   🧳 PLANEJADOR DE VIAGENS")
    print("=======================================")
    print("1 - Adicionar destino")
    print("2 - Adicionar passeio ao último destino")
    print("3 - Remover último item (passeio ou destino)")
    print("4 - Mostrar plano de viagem completo")
    print("5 - Sair")

    opcao = input("Escolha uma opção: ")

    # =========================================
    # OPÇÃO 1 - ADICIONAR DESTINO
    # =========================================
    if opcao == "1":
        destino = input("Digite o nome do destino: ")

        while True:
            valor_str = input(f"Digite o valor do destino {destino} (ex: 2.110,12): R$ ")
            valor = converter_valor(valor_str)
            if valor is not None:
                break
            print("❌ Valor inválido. Tente novamente (ex: 1.500,50 ou 1500.50).")

        pacote = {
            "destino": destino,
            "valor": valor,
            "passeios": [],
            "ultima_acao": "destino"  # para saber o que foi o último inserido
        }
        pilha_viagem.append(pacote)
        print(f"✅ Destino '{destino}' adicionado com valor de R$ {valor:,.2f}")

    # =========================================
    # OPÇÃO 2 - ADICIONAR PASSEIO AO ÚLTIMO DESTINO
    # =========================================
    elif opcao == "2":
        if len(pilha_viagem) == 0:
            print("⚠️ Nenhum destino disponível para adicionar passeios.")
        else:
            destino_atual = pilha_viagem[-1]
            print(f"\n🎯 Adicionando passeio ao destino atual: {destino_atual['destino']}")
            passeio = input("Digite o nome do passeio: ")

            while True:
                valor_passeio_str = input(f"Digite o valor do passeio '{passeio}' (ex: 250,00): R$ ")
                valor_passeio = converter_valor(valor_passeio_str)
                if valor_passeio is not None:
                    break
                print("❌ Valor inválido. Tente novamente (ex: 100,50 ou 100.50).")

            # Adiciona o passeio no destino atual
            destino_atual["passeios"].append({"passeio": passeio, "valor": valor_passeio})
            destino_atual["ultima_acao"] = "passeio"  # marca que o último item foi um passeio
            print(f"🧭 Passeio '{passeio}' adicionado (R$ {valor_passeio:,.2f}) ao destino '{destino_atual['destino']}'.")

    # =========================================
    # OPÇÃO 3 - REMOVER ÚLTIMO ITEM (LIFO)
    # =========================================
    elif opcao == "3":
        if len(pilha_viagem) == 0:
            print("⚠️ Nenhum destino ou passeio para remover.")
        else:
            destino_atual = pilha_viagem[-1]

            # Se o último destino tem passeios, removemos o último passeio primeiro
            if destino_atual["passeios"] and destino_atual["ultima_acao"] == "passeio":
                passeio_removido = destino_atual["passeios"].pop()
                print(f"🗑️ Passeio '{passeio_removido['passeio']}' removido do destino '{destino_atual['destino']}'.")

                # Verifica se ainda há passeios — se não, marca o topo como "destino"
                destino_atual["ultima_acao"] = "passeio" if destino_atual["passeios"] else "destino"

            else:
                # Se não há passeios, remove o próprio destino
                removido = pilha_viagem.pop()
                print(f"🗑️ Destino '{removido['destino']}' removido (R$ {removido['valor']:,.2f}).")

    # =========================================
    # OPÇÃO 4 - MOSTRAR PLANO COMPLETO
    # =========================================
    elif opcao == "4":
        if len(pilha_viagem) == 0:
            print("🕳️ Nenhum destino adicionado ainda.")
        else:
            print("\n🗺️ PLANO DE VIAGEM COMPLETO (de baixo para o topo):")
            total_geral = 0
            for i, pacote in enumerate(pilha_viagem):
                print(f"\n{i + 1}. ✈️ {pacote['destino']} - R$ {pacote['valor']:,.2f}")
                total_destino = pacote["valor"]

                if len(pacote["passeios"]) > 0:
                    print("   📍 Passeios:")
                    for p in pacote["passeios"]:
                        print(f"      - {p['passeio']} → R$ {p['valor']:,.2f}")
                        total_destino += p["valor"]

                print(f"   💵 Total desse destino: R$ {total_destino:,.2f}")
                total_geral += total_destino

            print("\n💰 TOTAL GERAL DA VIAGEM: R$ {:,.2f}".format(total_geral))
            print(f"➡️ Último destino (topo da pilha): {pilha_viagem[-1]['destino']}")

    # =========================================
    # OPÇÃO 5 - SAIR
    # =========================================
    elif opcao == "5":
        print("\n👋 Encerrando o planejador. Boa jornada!")
        break

    # =========================================pas
    # OPÇÃO INVÁLIDA
    # =========================================
    else:
        print("❌ Opção inválida. Tente novamente.")

